title: "Robo.Trico"
url: "https://khalidkordoba.github.io"
baseurl: ""
permalink: /article/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "artikel"

plugins:
  - jekyll-seo-tag